TinyClothes/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TinyClothes.Data;
using TinyClothes.Models;

namespace TinyClothes.Controllers
{
    public class CartController : Controller
    {
        private readonly StoreContext _context;
        private readonly IHttpContextAccessor _http;

        public CartController(StoreContext context, IHttpContextAccessor http)
        {
            _context = context;
            _http = http;
        }

        // Display all products in cart
        public IActionResult Index()
        {
            return View();
        }

        // Add a single product to the shopping cart
        public async Task<IActionResult> Add(int ID, string prevUrl)
        {
            Clothing c = await ClothingDB.GetClothingByID(ID, _context);

            if (c != null)
            {
                CartHelper.Add(c, _http);
            }

            // Use Redirect instead of RedirectToAction because prevUrl doesn't have an action tied to it
            return Redirect(prevUrl); 
        }

        public async void AddJS(int ID)
        {

        }

        // Summary / checkout page
        public IActionResult Checkout()
        {
            return View();
        }
    }
}

TinyClothes/Controllers/ClothingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TinyClothes.Data;
using TinyClothes.Models;

namespace TinyClothes.Controllers
{
    public class ClothingController : Controller
    {
        private readonly StoreContext _context;

        public ClothingController(StoreContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> InventoryList(int? page)
        {
            const int PageSize = 2;
            // Null coalescing operator
            int pageNumber = page ?? 1;
            ViewData["CurrentPage"] = pageNumber;

            ViewData["MaxPage"] = await GetMaxPage(PageSize);

            List<Clothing> clothes = await ClothingDB.GetClothingByPage(_context, pageNum: pageNumber, pageSize: PageSize);
            return View(clothes);
        }

        private async Task<int> GetMaxPage(int PageSize)
        {
            int numProducts = await ClothingDB.GetNumClothing(_context);
            int maxPage = Convert.ToInt32(Math.Ceiling((double)numProducts / PageSize));
            return maxPage;
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(Clothing c)
        {
            if (ModelState.IsValid)
            {
                await ClothingDB.Add(c, _context);
                // Temp data lasts for one redirect
                TempData["Message"] = $"{c.Title} added successfully";
                return RedirectToAction(nameof(InventoryList));
            }
            else
            {
                //Return same view with validation messages
                return View(c);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? ID)
        {
            if(ID == null)
            {
                // HTTP 400
                return BadRequest();
            }
            
            Clothing c = await ClothingDB.GetClothingByID(ID.Value, _context); // .Value can extract data out of a nullable data type

            if (c == null) // Clothing not in DB
            {
                // returns a HTTP 404 error - Not Found
                return NotFound();
            }

            return View(c);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Clothing c)
        {
            if(ModelState.IsValid)
            {
                await ClothingDB.Edit(c, _context);
                ViewData["Message"] = $"{c.Title} updated successfully";
                return View(c);
            }
            return View(c);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int ID)
        {
            Clothing c = await ClothingDB.GetClothingByID(ID, _context);

            if (c == null)
            {
                // returns a HTTP 404 error - Not Found
                return NotFound();
            }

            return View(c);
        }

        [HttpPost]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int ID)
        {
            Clothing c = await ClothingDB.GetClothingByID(ID, _context);

            await ClothingDB.Delete(c, _context);
            
            TempData["Message"] = $"{c.Title} deleted successfully";

            return RedirectToAction(nameof(InventoryList));
        }

        public async Task<IActionResult> Search(SearchCriteria search)
        {
            if (ModelState.IsValid)
            {
                if (search.IsBeingSearched())
                {
                    await ClothingDB.Search(search, _context);
                    return View(search);
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "You must search by at least 1 criteria. Otherwise, why are you even here?");
                    return View(search);
                }
            }

            return View();
        }
    }
}

TinyClothes/Views/Shared/_DisplayClothes.cshtml
@model IEnumerable<Clothing>
@inject IHttpContextAccessor  http

<table class="table text-light">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ItemID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Size)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Color)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ItemID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Size)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Color)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            @{
                // Get current url path "/Clothing/InventoryList"
                string prevUrl = http.HttpContext.Request.Path;
                // Add query string "?page=2"
                prevUrl += http.HttpContext.Request.QueryString.Value;
            }
        <td>
            @if (SessionHelper.IsUserLoggedIn(http))
            {
                <a class="btn btn-light text-dark" asp-action="Edit" asp-route-id="@item.ItemID">Edit</a>
                <a class="btn btn-danger text-light" asp-action="Delete" asp-route-id="@item.ItemID">Delete</a>
            }
            <a class="btn btn-success text-light" 
               data-cart-button
               data-cart-itemid ="@item.ItemID"
               asp-action="Add" 
               asp-controller="Cart" 
               asp-route-id="@item.ItemID" 
               asp-route-prevUrl="@prevUrl">Add to Cart</a>
        </td>
        </tr>
        }
    </tbody>
</table>

TinyClothes/Views/Shared/_Layout.cshtml
@inject IHttpContextAccessor sessionInfo
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tiny Clothes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css"/>
</head>
<body class="bg-dark text-light">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3 fixed-top">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TinyClothes</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex">
                    <ul class="navbar-nav flex-grow-1 ml-auto">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Clothing" asp-action="InventoryList">Inventory</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav flex-grow-1 justify-content-end">
                        @if (!SessionHelper.IsUserLoggedIn(sessionInfo))
                        {
                            <li class="nav-item">
                                <a class="btn btn-light nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register Now!</a>
                            </li>
                            <li class="nav-item">
                                <a class="btn btn-light nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="btn btn-light nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>
                        }
                        <li class="nav-item">
                            <span class="fas fa-shopping-cart fa-2x">@CartHelper.GetItemCount(sessionInfo)</span>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container" style="margin-top: 4em">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - TinyClothes - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>